### ISSUE TITLE
Assertion for float32/float64 comparison raised

### ISSUE THREAD

**Issue by mfeurer** [hyperopt/hyperopt-convnet#6]
When I run the code out of the box, I am confronted with the following error (this is just a snippet):

> File "/usr/local/lib/python2.7/dist-packages/hpconvnet/pyll_slm.py", line 492, in slm_fbncc_chmaj
> assert z.dtype == x.dtype, (z.dtype, x.dtype)
> AssertionError: ('float64', 'float32')

This happens when I run the experiment `shovel cifar10.small_random_run` on my cpu, but also on the gpu. I was able to fix the error by casting the type of z to float32, is this the right way to solve this problem?

**Comment by jaberg** [comment]
Thanks for the report. I typically run the worker command with
THEANO_FLAGS='floatX=float32' (actually I have it set that way in my
.theanorc) so does that help (as a workaround?)

**Comment by mfeurer** [comment]
Thanks for the fast answer. It work with this option. But you might consider adding the float-flag to the [example on the front page](https://github.com/jaberg/hyperopt-convnet#testing).
